In [7]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]


X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)
        
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

0 Cost: 2666.5378 
Prediction:
 [[204.37929]
 [242.17174]
 [240.62407]
 [261.3944 ]
 [184.01648]
 [133.51959]
 [195.09598]
 [144.11017]
 [224.33551]
 [205.5226 ]
 [187.60176]
 [182.95955]
 [249.41968]
 [207.96107]
 [195.34045]
 [245.34908]
 [197.77905]
 [234.84398]
 [238.42395]
 [213.41936]
 [228.81589]
 [226.53438]
 [218.63441]
 [207.87956]
 [252.02666]]
10 Cost: 22.698435 
Prediction:
 [[156.35197]
 [184.47107]
 [183.75769]
 [199.47174]
 [140.00867]
 [101.09126]
 [148.75157]
 [109.76218]
 [170.42674]
 [155.61224]
 [142.94904]
 [138.94498]
 [190.65993]
 [159.10307]
 [148.78757]
 [186.80295]
 [151.24452]
 [179.22641]
 [182.39984]
 [163.2902 ]
 [174.4699 ]
 [172.41077]
 [166.81517]
 [159.43571]
 [192.21855]]
20 Cost: 22.427668 
Prediction:
 [[156.00464 ]
 [184.07727 ]
 [183.35674 ]
 [199.04407 ]
 [139.70677 ]
 [100.885376]
 [148.43823 ]
 [109.53865 ]
 [170.07521 ]
 [155.3087  ]
 [142.64493 ]
 [138.65903 ]
 [190.23686 ]
 [158.74007 ]
 [148.47733 ]
 [186.40974 ]
 [150.89519 ]
 [178.85059 

520 Cost: 16.601072 
Prediction:
 [[155.30692]
 [184.28796]
 [182.99037]
 [199.05006]
 [139.7941 ]
 [101.69727]
 [148.75061]
 [110.16961]
 [171.01036]
 [157.16394]
 [142.84274]
 [139.47238]
 [189.46204]
 [157.58725]
 [148.99268]
 [186.91264]
 [149.63109]
 [179.2381 ]
 [181.02673]
 [162.02066]
 [174.47545]
 [172.57451]
 [166.61148]
 [157.43484]
 [191.66525]]
530 Cost: 16.508625 
Prediction:
 [[155.29462 ]
 [184.29166 ]
 [182.98389 ]
 [199.05025 ]
 [139.79555 ]
 [101.711685]
 [148.75632 ]
 [110.18111 ]
 [171.02698 ]
 [157.19699 ]
 [142.84633 ]
 [139.48686 ]
 [189.44824 ]
 [157.56667 ]
 [149.002   ]
 [186.9216  ]
 [149.60843 ]
 [179.24527 ]
 [181.00958 ]
 [162.00462 ]
 [174.48224 ]
 [172.58388 ]
 [166.61432 ]
 [157.40585 ]
 [191.66277 ]]
540 Cost: 16.416965 
Prediction:
 [[155.28235]
 [184.29536]
 [182.97745]
 [199.05045]
 [139.79698]
 [101.72603]
 [148.76202]
 [110.19257]
 [171.04352]
 [157.2299 ]
 [142.8499 ]
 [139.50128]
 [189.43452]
 [157.54617]
 [149.01128]
 [186.93053]
 [149.58586]


980 Cost: 13.084481 
Prediction:
 [[154.79651 ]
 [184.43903 ]
 [182.72038 ]
 [199.05916 ]
 [139.84917 ]
 [102.29495 ]
 [148.99373 ]
 [110.657616]
 [171.6993  ]
 [158.54053 ]
 [142.99353 ]
 [140.07466 ]
 [188.88603 ]
 [156.72618 ]
 [149.38467 ]
 [187.28427 ]
 [148.68013 ]
 [179.54422 ]
 [180.31165 ]
 [161.3531  ]
 [174.76244 ]
 [172.96326 ]
 [166.73386 ]
 [156.22594 ]
 [191.55893 ]]
990 Cost: 13.0226555 
Prediction:
 [[154.7866 ]
 [184.44191]
 [182.7151 ]
 [199.0594 ]
 [139.85013]
 [102.30659]
 [148.99858]
 [110.66736]
 [171.71269]
 [158.56741]
 [142.9965 ]
 [140.0864 ]
 [188.87476]
 [156.70929]
 [149.39241]
 [187.29149]
 [148.6614 ]
 [179.55038]
 [180.29768]
 [161.34009]
 [174.76813]
 [172.97083]
 [166.73634]
 [156.20232]
 [191.55678]]
1000 Cost: 12.961356 
Prediction:
 [[154.77673]
 [184.44476]
 [182.70985]
 [199.05957]
 [139.85107]
 [102.31813]
 [149.00342]
 [110.67704]
 [171.72601]
 [158.59416]
 [142.99947]
 [140.09808]
 [188.86353]
 [156.69247]
 [149.40013]
 [187.29868]
 [148.64276

1450 Cost: 10.689631 
Prediction:
 [[154.3779 ]
 [184.55794]
 [182.49617]
 [199.0689 ]
 [139.88493]
 [102.78573]
 [149.20403]
 [111.07899]
 [172.26492]
 [159.68129]
 [143.1208 ]
 [140.57198]
 [188.40526]
 [156.00514]
 [149.71696]
 [187.5895 ]
 [147.87811]
 [179.81288]
 [179.71713]
 [160.79994]
 [175.00801]
 [173.28288]
 [166.84288]
 [155.22173]
 [191.46486]]
1460 Cost: 10.648576 
Prediction:
 [[154.36996 ]
 [184.56013 ]
 [182.4919  ]
 [199.0691  ]
 [139.8855  ]
 [102.795044]
 [149.20815 ]
 [111.087204]
 [172.27565 ]
 [159.70303 ]
 [143.12326 ]
 [140.58144 ]
 [188.39607 ]
 [155.9913  ]
 [149.72337 ]
 [187.59528 ]
 [147.86267 ]
 [179.81816 ]
 [179.70578 ]
 [160.78938 ]
 [175.01277 ]
 [173.28894 ]
 [166.84505 ]
 [155.20256 ]
 [191.463   ]]
1470 Cost: 10.607896 
Prediction:
 [[154.36208 ]
 [184.56233 ]
 [182.48766 ]
 [199.06932 ]
 [139.88606 ]
 [102.804306]
 [149.21223 ]
 [111.09539 ]
 [172.28633 ]
 [159.72467 ]
 [143.1257  ]
 [140.59085 ]
 [188.38692 ]
 [155.97755 ]
 [149.72975 ]
 [187.60

1980 Cost: 8.9381485 
Prediction:
 [[154.0056  ]
 [184.65833 ]
 [182.2938  ]
 [199.07997 ]
 [139.90659 ]
 [103.222824]
 [149.4028  ]
 [111.47648 ]
 [172.76863 ]
 [160.70848 ]
 [143.23787 ]
 [141.01788 ]
 [187.9687  ]
 [155.34787 ]
 [150.0241  ]
 [187.86139 ]
 [147.141   ]
 [180.07076 ]
 [179.17976 ]
 [160.3018  ]
 [175.23743 ]
 [173.56798 ]
 [166.94914 ]
 [154.31493 ]
 [191.3738  ]]
1990 Cost: 8.9122305 
Prediction:
 [[153.99945]
 [184.65993]
 [182.2904 ]
 [199.08018]
 [139.90685]
 [103.23006]
 [149.40622]
 [111.48329]
 [172.77696]
 [160.72559]
 [143.23985]
 [141.0253 ]
 [187.9614 ]
 [155.33684]
 [150.0293 ]
 [187.86589]
 [147.12857]
 [180.07521]
 [179.17078]
 [160.2935 ]
 [175.24133]
 [173.57271]
 [166.951  ]
 [154.2998 ]
 [191.37221]]
2000 Cost: 8.886517 
Prediction:
 [[153.99333]
 [184.66151]
 [182.28705]
 [199.08037]
 [139.90709]
 [103.23726]
 [149.40962]
 [111.49007]
 [172.78526]
 [160.74263]
 [143.24182]
 [141.03268]
 [187.95412]
 [155.32585]
 [150.03447]
 [187.87038]
 [147.1162 

In [ ]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))
