In [2]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  271849.12 
Prediction:
 [-314.73804 -369.40912 -369.014   -396.90192 -283.5381 ]
10 Cost:  9.827926 
Prediction:
 [146.49168 184.94637 177.20631 197.91655 139.29494]
20 Cost:  7.330963 
Prediction:
 [147.89162 186.62076 178.86049 199.71617 140.57146]
30 Cost:  7.3226066 
Prediction:
 [147.90024 186.62294 178.86699 199.72151 140.57253]
40 Cost:  7.314266 
Prediction:
 [147.90468 186.62007 178.86853 199.72145 140.56975]
50 Cost:  7.3060007 
Prediction:
 [147.90903 186.61716 178.87    199.72131 140.56694]
60 Cost:  7.297719 
Prediction:
 [147.91342 186.6143  178.87152 199.72122 140.5642 ]
70 Cost:  7.2894735 
Prediction:
 [147.9178  186.61142 178.873   199.72112 140.56142]
80 Cost:  7.281321 
Prediction:
 [147.92216 186.6086  178.87451 199.72104 140.55867]
90 Cost:  7.273156 
Prediction:
 [147.9265  186.60571 178.87598 199.72092 140.55591]
100 Cost:  7.2650237 
Prediction:
 [147.93082 186.60284 178.87746 199.7208  140.55316]
110 Cost:  7.2569075 
Prediction:
 [147.93513 186.59999

1350 Cost:  6.4365196 
Prediction:
 [148.39903 186.29663 179.0397  199.69244 140.27429]
1360 Cost:  6.431113 
Prediction:
 [148.40224 186.29453 179.04082 199.6921  140.27249]
1370 Cost:  6.425719 
Prediction:
 [148.40544 186.29242 179.04195 199.69176 140.2707 ]
1380 Cost:  6.4203215 
Prediction:
 [148.40865 186.29034 179.04306 199.6914  140.26894]
1390 Cost:  6.4149675 
Prediction:
 [148.41185 186.28827 179.0442  199.6911  140.2672 ]
1400 Cost:  6.409608 
Prediction:
 [148.41505 186.28622 179.04536 199.69078 140.26546]
1410 Cost:  6.40427 
Prediction:
 [148.41824 186.28416 179.04646 199.69044 140.26372]
1420 Cost:  6.3989706 
Prediction:
 [148.4214  186.28209 179.04758 199.69011 140.26198]
1430 Cost:  6.3936663 
Prediction:
 [148.42458 186.28004 179.0487  199.68977 140.26024]
1440 Cost:  6.3883643 
Prediction:
 [148.42773 186.27797 179.0498  199.68942 140.2585 ]
1450 Cost:  6.383082 
Prediction:
 [148.4309  186.27592 179.05092 199.68909 140.25679]
1460 Cost:  6.3778214 
Prediction:
 [1

In [3]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')


hypothesis = tf.matmul(X, W) + b


cost = tf.reduce_mean(tf.square(hypothesis - Y))


optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  4087.037 
Prediction:
 [[ 99.45661 ]
 [113.128136]
 [114.39983 ]
 [128.72215 ]
 [ 81.34423 ]]
10 Cost:  28.468983 
Prediction:
 [[155.79454]
 [180.87555]
 [181.13525]
 [201.39603]
 [133.02618]]
20 Cost:  28.310963 
Prediction:
 [[155.94746]
 [181.09267]
 [181.33194]
 [201.61092]
 [133.19951]]
30 Cost:  28.190744 
Prediction:
 [[155.93045]
 [181.10544]
 [181.32735]
 [201.60661]
 [133.21696]]
40 Cost:  28.071121 
Prediction:
 [[155.91298]
 [181.11757]
 [181.32216]
 [201.60164]
 [133.2339 ]]
50 Cost:  27.952236 
Prediction:
 [[155.89552]
 [181.12962]
 [181.31696]
 [201.59665]
 [133.25075]]
60 Cost:  27.833826 
Prediction:
 [[155.87813]
 [181.14166]
 [181.31177]
 [201.59167]
 [133.2676 ]]
70 Cost:  27.716187 
Prediction:
 [[155.8608 ]
 [181.15369]
 [181.30663]
 [201.58675]
 [133.28438]]
80 Cost:  27.599041 
Prediction:
 [[155.8435 ]
 [181.16568]
 [181.30151]
 [201.58182]
 [133.30115]]
90 Cost:  27.482655 
Prediction:
 [[155.82626]
 [181.1776 ]
 [181.29636]
 [201.57687]
 [133.31783

1040 Cost:  18.799143 
Prediction:
 [[154.38954]
 [182.17412]
 [180.87086]
 [201.15483]
 [134.72198]]
1050 Cost:  18.728819 
Prediction:
 [[154.37633]
 [182.18324]
 [180.86696]
 [201.1508 ]
 [134.73497]]
1060 Cost:  18.658775 
Prediction:
 [[154.36322]
 [182.19241]
 [180.86311]
 [201.14685]
 [134.748  ]]
1070 Cost:  18.589142 
Prediction:
 [[154.35008]
 [182.20148]
 [180.85922]
 [201.14282]
 [134.76093]]
1080 Cost:  18.519886 
Prediction:
 [[154.33702]
 [182.21059]
 [180.8554 ]
 [201.13887]
 [134.77385]]
1090 Cost:  18.450983 
Prediction:
 [[154.32399]
 [182.21962]
 [180.85153]
 [201.13489]
 [134.78673]]
1100 Cost:  18.382444 
Prediction:
 [[154.31096]
 [182.22864]
 [180.84769]
 [201.13092]
 [134.79956]]
1110 Cost:  18.31421 
Prediction:
 [[154.29805]
 [182.2377 ]
 [180.84392]
 [201.12701]
 [134.81242]]
1120 Cost:  18.246387 
Prediction:
 [[154.2851 ]
 [182.24663]
 [180.84007]
 [201.12303]
 [134.82518]]
1130 Cost:  18.178844 
Prediction:
 [[154.27223]
 [182.25562]
 [180.83629]
 [201.11